build: enhance build & deploy tasks

diff --git a/bin/deploy-to-s3 b/bin/deploy-to-s3
--- a/bin/deploy-to-s3
+++ b/bin/deploy-to-s3
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
 # Package S3 uploader
-# 
+#
 # Usage: bin/deploy-to-s3 [<package_name>, ...]
-# 
+#
 # If you pass package names, it will look for specific packages on the output
 # directory and will try to build them. Otherwise, it will upload all packages
 # in that directory.
@@ -63,10 +63,11 @@ upload_package() {
   package=$1
 
   # Set the output folder of the built package
-  export PKGDEST="$OUTPUT_PATH"
+  export PKGDEST="$OUTPUT_PATH/packages"
 
   # Get the name of the built package
   built_pkg_file=$(cd "src/$package" && makepkg --packagelist)
+  built_pkg_basename="${built_pkg_file#$PKGDEST/}"
 
   if ! [ -f "$built_pkg_file" ]; then
     error "The package '$package' is not built!"
@@ -74,39 +75,68 @@ upload_package() {
   fi
 
   # Upload it!
-  upload_file "${built_pkg_file#$PKGDEST/}"
+  upload_artifact packages "$built_pkg_basename"
+
+  # Delete the old versions of that package on the remote
+  delete_old_versions "$package" "$built_pkg_basename"
 }
 
 upload_repo_db() {
   files="$REPO_NAME.db $REPO_NAME.db.tar.gz $REPO_NAME.files $REPO_NAME.files.tar.gz"
 
   for file in $files; do
-    upload_file "$file"
+    upload_artifact db "$file"
   done
 }
 
-upload_file() {
-  file=$1
+delete_old_versions() {
+  package_name=$1
+  built_package_name=$2
+
+  packages_to_delete=$(aws s3 ls "$AWS_S3_BUCKET_NAME/$package_name-" | awk "!/$built_package_name/ { print \$4 }")
+
+  for filename in $packages_to_delete; do
+    success "Removing old package $filename"
+    aws s3 rm "s3://$AWS_S3_BUCKET_NAME/$filename" > /dev/null
+    info "File $filename removed from repository"
+  done
+}
+
+# This function uploads an artifact at the `output` path to the S3 bucket.
+# Please notice that the file will be uploaded to the root path of the bucket
+# plus the name of the file (second argument). The folder argument only
+# specifies where to find the file.
+#
+# Arguments
+#  1 - This is the folder where to find the file
+#  2 - This is the file that you want to upload
+upload_artifact() {
+  folder=$1
+  file=$2
 
   # Avoid re-uploading packages that are already there
   s3_md5=$(aws s3api head-object --bucket "$AWS_S3_BUCKET_NAME" --key "$file" \
-    --query ETag --output text | grep --extended --only-match '[a-f0-9]{32}')
+    --query ETag --output text 2> /dev/null | grep --extended --only-match \
+    '[a-f0-9]{32}'); status=$?
 
-  file_md5=$(md5sum "$OUTPUT_PATH/$file" | \
-    grep --extended --only-match '[a-f0-9]{32}')
+  if [ $status -eq 0 ]; then
+    file_md5=$(md5sum "$OUTPUT_PATH/$folder/$file" | \
+      grep --extended --only-match '[a-f0-9]{32}')
 
-  if [ "$s3_md5" = "$file_md5" ]; then
-    warn "File '$file' already uploaded."
-    return
+    if [ "$s3_md5" = "$file_md5" ]; then
+      warn "File '$folder/$file' already uploaded."
+      return
+    fi
   fi
 
-  aws s3 cp "$OUTPUT_PATH/$file" "s3://$AWS_S3_BUCKET_NAME/$file" > /dev/null
+  success "Uploading file $folder/$file"
+  aws s3 cp "$OUTPUT_PATH/$folder/$file" "s3://$AWS_S3_BUCKET_NAME/$file" > /dev/null
   status=$?
 
   if [ $status -eq 0 ]; then
-    success "File '$file' uploaded"
+    info "File '$folder/$file' uploaded"
   else
-    error "The file '$file' could not be uploaded."
+    error "The file '$folder/$file' could not be uploaded."
     exit 1
   fi
 }
@@ -116,10 +146,12 @@ bold=$(tput bold)
 red=$(tput setaf 1)
 green=$(tput setaf 2)
 orange=$(tput setaf 3)
+blue=$(tput setaf 4)
 normal=$(tput sgr0)
 error() { echo "${bold}${red}==> ERROR:${normal}${bold} ${*}${normal}"; }
 success() { echo "${bold}${green}==>${normal}${bold} ${*}${normal}"; }
 warn() { echo "${bold}${orange}==> WARNING:${normal}${bold} ${*}${normal}"; }
+info() { echo "${bold}${blue}  ->${normal}${bold} ${*}${normal}"; }
 
 # shellcheck disable=SC2068
 main $@
