ci: pull the repo from s3 instead of using circle cache

diff --git a/bin/pull-repo-from-s3 b/bin/pull-repo-from-s3
--- a/bin/pull-repo-from-s3
+++ b/bin/pull-repo-from-s3
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
-# Pull GPG sign key from S3 bucket
+# Pull the repository files from S3
 #
-# Usage: bin/pull-sign-key-from-s3
+# Usage: bin/pull-repo-from-s3
 #
-# This will pull the private signing key from S3 and import it onto the local
-# GPG keyring.
+# This will pull the repository files from the S3 bucket. This is useful
+# because we want to make delta builds.
 #
 # Environment:
 #   (Optional) AWS_PROFILE => Set which AWS profile is going to be used to
@@ -15,8 +15,8 @@
 #     point to the key created by IAM.
 #   (Optional) AWS_SECRET_ACCESS_KEY => If not using AWS profiles, this should
 #     be the access secret of your key.
-#   (Required) AWS_S3_SECRET_BUCKET_NAME => The bucket name where the GPG sign
-#     key is stored.
+#   (Required) AWS_S3_PACKAGES_BUCKET_NAME => The bucket name where the
+#     packages are stored.
 #   (Required) REPO_NAME => The name of the repository file that you want to
 #     add your built packages to.
 #
@@ -28,8 +28,8 @@ main() {
   # cd to root path
   cd "$(dirname "$0")/.." || exit
 
-  if [ -z "$AWS_S3_SECRET_BUCKET_NAME" ]; then
-    error "Please, set the S3 Bucket using the variable \$AWS_S3_SECRET_BUCKET_NAME"
+  if [ -z "$AWS_S3_PACKAGES_BUCKET_NAME" ]; then
+    error "Please, set the S3 Bucket using the variable \$AWS_S3_PACKAGES_BUCKET_NAME"
     exit 1
   fi
 
@@ -38,39 +38,26 @@ main() {
     exit 1
   fi
 
-  tmp_dir="$(mktemp -d)"
-  key_path="$tmp_dir/gpg-key.asc"
-
-  # Get the secret file from AWS S3
-  pull_into "$key_path"
-
-  # Then import it onto the GPG keyring
-  import_into_gpg_keyring "$key_path"
-
-  # Then remove the tempdir
-  rm -rf "$tmp_dir"
+  # Get the repo from the S3
+  pull_into "output/db"
 }
 
 pull_into() {
-  path=$1
+  dir=$1
+  files="$REPO_NAME.db $REPO_NAME.db.tar.gz $REPO_NAME.files $REPO_NAME.files.tar.gz"
 
-  success "Pulling the GPG secret key from S3 bucket"
-  aws s3 cp "s3://$AWS_S3_SECRET_BUCKET_NAME/sign-key-for-$REPO_NAME.asc" \
-    "$path" 2> /dev/null; status=$?
+  success "Pulling the repo from S3 bucket"
+  for file in $files; do
+    aws s3 cp "s3://$AWS_S3_PACKAGES_BUCKET_NAME/$file" \
+      "$dir/$file" 2> /dev/null; status=$?
 
-  if [ "$status" != 0 ]; then
-    error "Failed to pull the GPG key from the S3!"
-    exit 1
-  fi
+    if [ "$status" != 0 ]; then
+      error "Failed to pull the repo file '$file' from the S3!"
+      exit 1
+    fi
+  done
 
   info "Success!"
-}
-
-import_into_gpg_keyring() {
-  path=$1
-
-  success "Importing the GPG secret key to the keyring"
-  gpg --import "$path"
 }
 
 # Print colorful notice messages to the console
